RU = {
    "fake.usage_pipe": "Формат: .fake Имя | @ник | Текст",
    "fake.no_text": "В сообщении нет текста для карточки.",
    "fake.usage_reply": "Формат: .fake Имя | @ник | Текст, либо ответом на сообщение собеседника.",
    "fake.watermark": "🛠 шаблон, сгенерировано ботом",
    "cmdmeta.fake.title": "Фейк-пост",
    "cmdmeta.fake.short": "Создаёт шаблон карточки поста",
    "cmdmeta.fake.long": "Генерирует карточку в стиле поста из соцсети с именем, ником и текстом — либо из параметров через |, либо ответом на сообщение собеседника (тогда берёт его имя, ник и аватар).",
    "cmdmeta.fake.usage": ".fake Имя | @ник | Текст",
}

EN = {
    "fake.usage_pipe": "Format: .fake Name | @handle | Text",
    "fake.no_text": "There's no text in this message for the card.",
    "fake.usage_reply": "Format: .fake Name | @handle | Text, or reply to a message from the other person.",
    "fake.watermark": "🛠 template, generated by the bot",
    "cmdmeta.fake.title": "Fake post",
    "cmdmeta.fake.short": "Creates a post card template",
    "cmdmeta.fake.long": "Generates a social-media-style post card with a name, handle and text — either from pipe-separated arguments or as a reply (then it uses the other person's name, handle and avatar).",
    "cmdmeta.fake.usage": ".fake Name | @handle | Text",
}

UK = {
    "fake.usage_pipe": "Формат: .fake Ім'я | @нік | Текст",
    "fake.no_text": "У повідомленні немає тексту для картки.",
    "fake.usage_reply": "Формат: .fake Ім'я | @нік | Текст, або у відповідь на повідомлення співрозмовника.",
    "fake.watermark": "🛠 шаблон, згенеровано ботом",
    "cmdmeta.fake.title": "Фейк-пост",
    "cmdmeta.fake.short": "Створює шаблон картки поста",
    "cmdmeta.fake.long": "Генерує картку у стилі посту із соцмережі з ім'ям, ніком і текстом — або з параметрів через |, або у відповідь на повідомлення співрозмовника (тоді бере його ім'я, нік і аватар).",
    "cmdmeta.fake.usage": ".fake Ім'я | @нік | Текст",
}
