"""Автоматически сгенерировано scripts/split_locales.py."""

RU = {
    "fake.usage_pipe": "Формат: .fake Имя | @ник | Текст",
    "fake.no_text": "В сообщении нет текста для карточки.",
    "fake.usage_reply": "Формат: .fake Имя | @ник | Текст, либо ответом на сообщение собеседника.",
    "fake.watermark": "🛠 шаблон, сгенерировано ботом",
    "cmddesc.fake": "Создаёт шаблон карточки поста",
}

EN = {
    "fake.usage_pipe": "Format: .fake Name | @handle | Text",
    "fake.no_text": "There's no text in this message for the card.",
    "fake.usage_reply": "Format: .fake Name | @handle | Text, or reply to a message from the other person.",
    "fake.watermark": "🛠 template, generated by the bot",
    "cmddesc.fake": "Creates a post card template",
}

UK = {
    "fake.usage_pipe": "Формат: .fake Ім'я | @нік | Текст",
    "fake.no_text": "У повідомленні немає тексту для картки.",
    "fake.usage_reply": "Формат: .fake Ім'я | @нік | Текст, або у відповідь на повідомлення співрозмовника.",
    "fake.watermark": "🛠 шаблон, згенеровано ботом",
    "cmddesc.fake": "Створює шаблон картки поста",
}
